// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginData struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginData) Reset()         { *m = LoginData{} }
func (m *LoginData) String() string { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()    {}
func (*LoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_750fcebfee51479e, []int{0}
}
func (m *LoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginData.Unmarshal(m, b)
}
func (m *LoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginData.Marshal(b, m, deterministic)
}
func (dst *LoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginData.Merge(dst, src)
}
func (m *LoginData) XXX_Size() int {
	return xxx_messageInfo_LoginData.Size(m)
}
func (m *LoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginData proto.InternalMessageInfo

func (m *LoginData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_750fcebfee51479e, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_750fcebfee51479e, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginData)(nil), "twirp.auth.LoginData")
	proto.RegisterType((*User)(nil), "twirp.auth.User")
	proto.RegisterType((*Response)(nil), "twirp.auth.Response")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_auth_750fcebfee51479e) }

var fileDescriptor_auth_750fcebfee51479e = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x50, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x65, 0x77, 0xd3, 0x65, 0x77, 0x04, 0x91, 0x61, 0x17, 0xca, 0x9e, 0xa4, 0x78, 0xf0, 0x14,
	0xa1, 0x7a, 0xd4, 0x83, 0x22, 0x9e, 0x3c, 0x05, 0xbc, 0x78, 0x8b, 0x34, 0xd8, 0xa0, 0x4d, 0x42,
	0x92, 0xd2, 0xbf, 0x6f, 0x33, 0xb5, 0x1f, 0x08, 0x5e, 0xc2, 0xbc, 0x37, 0x1f, 0xef, 0xe5, 0xc1,
	0xd1, 0x79, 0x1b, 0xed, 0x8d, 0x6c, 0x63, 0x4d, 0x0f, 0x27, 0x8c, 0x10, 0x3b, 0xed, 0x1d, 0x4f,
	0x4c, 0xf1, 0x00, 0xfb, 0x57, 0xfb, 0xa9, 0xcd, 0xb3, 0x8c, 0x12, 0x0f, 0x90, 0xa9, 0x46, 0xea,
	0xef, 0x7c, 0x75, 0xb9, 0xba, 0xde, 0x8b, 0x01, 0xe0, 0x09, 0x76, 0x4e, 0x86, 0xd0, 0x59, 0x5f,
	0xe5, 0x6b, 0x6a, 0x4c, 0xb8, 0xf0, 0xc0, 0xde, 0x82, 0xf2, 0x78, 0x0e, 0x6b, 0x5d, 0xd1, 0xda,
	0x46, 0xf4, 0x15, 0x22, 0x30, 0x23, 0x1b, 0xf5, 0x3b, 0x4f, 0x75, 0xba, 0xee, 0x6a, 0x6b, 0x54,
	0xbe, 0x19, 0xae, 0x13, 0x98, 0x35, 0xd9, 0x7f, 0x9a, 0xd9, 0x1f, 0xcd, 0x17, 0xd8, 0x09, 0x15,
	0x9c, 0x35, 0x81, 0xb6, 0xa3, 0xfd, 0x52, 0x66, 0x74, 0x4c, 0x00, 0xaf, 0x80, 0xb5, 0xbd, 0x2b,
	0x52, 0x3f, 0x2b, 0x2f, 0xf8, 0xfc, 0x5f, 0x9e, 0xdc, 0x0a, 0xea, 0x96, 0xf7, 0xc0, 0x1e, 0x7b,
	0x0a, 0xef, 0x20, 0xa3, 0x08, 0xf0, 0xb8, 0x1c, 0x9c, 0x52, 0x39, 0x1d, 0x96, 0xf4, 0xa8, 0xfc,
	0xb4, 0x7d, 0x67, 0x89, 0xf8, 0xd8, 0x52, 0xa6, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7c,
	0xb4, 0x54, 0x8b, 0x6c, 0x01, 0x00, 0x00,
}
